const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
function toast(m){let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';t.setAttribute('role','status');document.body.append(t)}t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
$('#mobileMenuOpen')?.addEventListener('click',()=>toast('Mobile navigation — xem đầy đủ trong Homepage prototype'));
$('#searchOpen')?.addEventListener('click',()=>toast('Global Search — Ctrl/Cmd + K trên Homepage'));
$$('[data-demo-contact]').forEach(b=>b.addEventListener('click',()=>toast('Đã mở luồng liên hệ mô phỏng')));
const qs=new URLSearchParams(location.search);
if($('#innerSearch')){$('#innerSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('[data-searchable]').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(q))})}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{const g=b.closest('.pill-tabs');g&&$$('button',g).forEach(x=>x.classList.remove('active'));b.classList.add('active');const v=b.dataset.filter;$$('[data-category]').forEach(x=>x.hidden=v!=='all'&&x.dataset.category!==v)}));
$$('[data-office]').forEach(b=>b.addEventListener('click',()=>{$$('[data-office]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=officeData[b.dataset.office]||officeData.q1;$('#officeImage').src=d.image;$('#officeName').textContent=d.name;$('#officeText').textContent=d.text}));
const officeData={q1:{name:'QTSC Building 1',text:'Trụ sở QTSC · văn phòng · tiện ích nội khu',image:'https://info.qtsc.com.vn/upload/contents/qtscbuilding-B811722321392.webp'},helios:{name:'Helios Building',text:'Không gian văn phòng trong campus công nghệ',image:'https://www.qtsc.com.vn/uploads/files/2021/03/14/1-goc-Cong-vien-phan-mem-Quang-Trung-02.jpg'},sbi:{name:'SBI Building',text:'Kết nối doanh nghiệp và hệ tiện ích QTSC',image:'https://www.qtsc.com.vn/uploads/files/2018/02/12/thumbs-1200-628-2--1/qtsc_flycam_640x320.jpg'}};
$$('.place-card').forEach((c,i)=>c.addEventListener('click',()=>{$$('.place-card').forEach(x=>x.classList.remove('active'));c.classList.add('active');$$('.explore-pin').forEach(x=>x.style.boxShadow='0 0 0 9px rgba(241,118,44,.18)');const p=$$('.explore-pin')[i];if(p)p.style.boxShadow='0 0 0 15px rgba(241,118,44,.25),0 0 25px rgba(241,118,44,.6)'}));
